### ISSUE TITLE
How to get the IP address field of an NSG that is present in the Monitoring Console ?

### ISSUE THREAD

**Issue by arnaudcoquelet** [nuagenetworks/vspk#1]
Is there a way to get the IP address field of an NSG that is present in the Monitoring Console ?

From the VSP object, I can get the information regarding the VSCs, HSCs and VRSs but I don't find a way to get the info of the NSGs (I tried with Nuage 3.2R2).
In the VSD Gui, it seems the NSGs are considered as VRS but through the vspk the VRSS is an empty array.

![screen shot 2015-08-29 at 3 23 57 pm](https://cloud.githubusercontent.com/assets/39832/9563908/211f7cf6-4e62-11e5-964b-0fd6c5a194fc.png)

The main idea is to be able to have something like a whitelist of IP addresses for the NSGs that are deployed. And if one NSG appears to be from an unknown IP, send an alarm to a monitoring system (like to prevent someone stilling the NSG and putting it at home).

The feature that deactivate after a certain time the NSG in case of been unreachable is good, but if there is a power/wan outage longer than let say 6H (which can happen), someone will need to go on site to reactivate it, which may not be practical for our customer.

Thanks

**Comment by pdellaert** [comment]
It seems like there is a small bug with fetching the VRSs using the vspk. I reported this (https://github.com/nuagenetworks/bambou/issues/1) and proposed a fix (https://github.com/nuagenetworks/bambou/pull/2) 

I don't have NSGs in my test environment, but i assume you will get those as well, as in the code, it mentions the possibility of the personality property to be NSG.

**Comment by arnaudcoquelet** [comment]
Thanks Philippe, I made the change and I can fetch the NSG information.

**Comment by pdellaert** [comment]
Another fix is to edit https://github.com/nuagenetworks/vspk/blob/master/vsdk/v3_2/nuvrs.py and add ```__rest_name__ = u"vrss"```

My previous way is a bit dirty, so it won't be pulled.

**Comment by primalmotion** [comment]
it's dangerous to change the `rest_name`. It's like crossing the streams: it's bad :)

In the same file as described above, simply add an override to `rest_resource_name`

```
    @property
    def rest_resource_name(cls):
        return "vrss"
```

That should do the trick.

**Comment by primalmotion** [comment]
@t00f can you provide a clean fix for this?

Thanks!

**Comment by pdellaert** [comment]
@primalmotion Sadly your fix doesn't seem to work, as in https://github.com/nuagenetworks/bambou/blob/master/bambou/nurest_object.py#L357 you have the following code for getting the URL to fetch children (so for instance VRSs)

```python
def get_resource_url(self):
        """ Get resource complete url """

        name = self.__class__.rest_resource_name
        url = self.__class__.rest_base_url()

        if self.id is not None:
            return "%s/%s/%s" % (url, name, self.id)

        return "%s/%s" % (url, name)

    def get_resource_url_for_child_type(self, nurest_object_type):
        """ Get the resource url for the nurest_object type """

        return "%s/%s" % (self.get_resource_url(), nurest_object_type.rest_resource_name)
```

So it directly uses the ```rest_resource_name``` from the metaclass. (https://github.com/nuagenetworks/bambou/blob/master/bambou/nurest_object.py#L58)

I'm sure there is an elegant solution, but my python knowledge doesn't extend into Metaclasses (I'm not a developer ;)). Haven't found a way to override the Metaclass ```rest_resource_name```

**Comment by primalmotion** [comment]
Ok, well I'll check that out next week when I'll be back but I'm sure @t00f will come with a working solution sooner :) 

In the meantime your first hack on bambou is actually safer than changing the rest name so I would recommend to do this for now.

**Comment by primalmotion** [comment]
This should be fixed with the latest master of bambou.
